name: Action Pull_Request
on: 
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  log-context:
    runs-on: ubuntu-latest
    steps:
      - name: Log github
        run: echo "${{toJSON(github)}}"
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: git checkout
        uses: actions/checkout@v3
      - name: run npm ci
        run: npm ci
      - name: run npm lint
        run: npm run lint
      - name: run npm build
        run: npm run build
      - name: run npm test
        run: echo "npm run test"
