name: Action Run Pipeline
on: 
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  log-context:
    runs-on: ubuntu-latest
    steps:
      - name: Log github
        run: echo "${{toJSON(github)}}"
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: git checkout
        uses: actions/checkout@v3
      - name: run npm ci
        run: npm ci
      - name: run npm lint
        run: npm run lint
      - name: run npm test
        run: echo "npm run test"
  build:
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - name: git checkout
        uses: actions/checkout@v3
      - name: run npm ci
        run: npm ci
      - name: run npm build
        run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: run npm ci
        run: npm ci
      - name: run npm build
        run: npm run build
      - name: run npm ci/cd
        run: echo "pipeline running..."