name: Pull_Request - Valid Title
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  pr-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Check if title, branch, or description contains "PR:"
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BRANCH="${{ github.event.pull_request.head.ref }}"
          PR_DESCRIPTION="${{ github.event.pull_request.body }}"
          
          echo "Pull Request Title: $PR_TITLE"
          echo "Pull Request Branch: $PR_BRANCH"
          echo "Pull Request Description: $PR_DESCRIPTION"

          if [[ ! "$PR_TITLE" =~ [Pp][Rr]: && ! "$PR_BRANCH" =~ [Pp][Rr]: && ! "$PR_DESCRIPTION" =~ [Pp][Rr]: ]]; then
            echo "Error: Either the title, branch name, or description must contain 'PR:' (case-insensitive)"
            exit 1
          fi