name: Pull_Request - Validate Title/Branch/Description
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  pr-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Check Title,Branch,Description Must Contains Ticket Key "PR-12345"
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BRANCH="${{ github.event.pull_request.head.ref }}"
          PR_DESCRIPTION="${{ github.event.pull_request.body }}"
          
          echo "Pull Request Title: $PR_TITLE"
          echo "Pull Request Branch: $PR_BRANCH"
          echo "Pull Request Description: $PR_DESCRIPTION"

          # Regex to match "PR-" followed by 4 digits
          if [[ ! "$PR_TITLE" =~ PR-[0-9]{1,5} && ! "$PR_BRANCH" =~ PR-[0-9]{1,5} && ! "$PR_DESCRIPTION" =~ PR-[0-9]{1,5} ]]; then
            echo "Error: Either the title, branch name, or description must contain 'PR-****' (e.g., PR-1234)"
            exit 1
          fi